- hosts: all
  become: true
  tasks:

  - name: Installing required packages
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - zlib1g-dev
      - libffi-dev
      - build-essential

  #-----------------------+
  # Setting up python env |
  #-----------------------+
  - name: Calling build-python role ...
    import_role:
      name: ../../roles/build-python
    vars:
      python_version: 3.7.4

  - name: "Downloading numpy library"
    get_url:
      url: http://aptmirror.kaleyra.com/python/pypi/numpy-1.17.2-cp37-cp37m-manylinux1_x86_64.whl
      dest: /tmp/

  - name: "installing numpy"
    command: pip3.7 install /tmp/numpy-1.17.2-cp37-cp37m-manylinux1_x86_64.whl

  - name: "Downloading netifaces module for python"
    unarchive:
      src: http://aptmirror.kaleyra.com/python/pypi/netifaces-0.10.9.tar.gz
      dest: /tmp/
      remote_src: yes

  - name: "Installing netifaces"
    shell: python3.7 setup.py install
    args:
      chdir: /tmp/netifaces-0.10.9/

  #------------------------+
  # killing server if is up|
  #------------------------+
  - name: "looking for server pid"
    shell: ps aux | grep pybootd.py | grep -v grep | awk '{ print $2 }'
    register: pybootd_pid
    ignore_errors: yes

  - name: "killing the server"
    command: kill -9 "{{ pybootd_pid.stdout }}"
    ignore_errors: yes

  #-----------------------+
  # uplo. & templ. server |
  #-----------------------+
  - name: "Uploading BOOTP/TFTP/PXE python server on the remote helper"
    synchronize:
      src: ../roles/vm-deploy/files/linux/pybootd/
      dest: /dev/shm/pybootd/

  - name: "Uploading debian image for the selected virtual machine OS"
    synchronize:
      src: "../roles/vm-deploy/files/linux/images/{{vm_os}}"
      dest: "/dev/shm/pybootd/images/"

  - name: "Uploading Preseed file"
    copy:
      src: "../roles/vm-deploy/files/linux/preseed.cfgs/preseed.cfg"
      dest: "/dev/shm/pybootd/images/{{vm_os}}/debian-installer/amd64/preseed.cfg"

  #getting net info from the helper machine
  - name: "Netinfo: get network gateway"
    shell: cat /etc/network/interfaces | grep gateway | awk '{ print $2 }' | awk -F "/" '{ print $1 }'
    register: net_gateway

  - name: "Netinfo: get helper address"
    shell: cat /etc/network/interfaces | grep address | awk '{ print $2 }' | awk -F "/" '{ print $1 }'
    register: helper_address

  - name: "Netinfo: get network nameservers"
    shell: cat /etc/resolv.conf | grep name | awk '{print $2}' | head -1
    register: net_dns

  - name: "Netinfo: get search address"
    shell: cat /etc/resolv.conf | grep search | awk '{print $2}'
    register: net_domain

  #templating server configuration files with collected information
  - name: "templating DHCP server configuration file"
    template:
      src: ../roles/vm-deploy/templates/linux/etc/pybootd.ini
      dest: /dev/shm/pybootd/pybootd/etc/pybootd.ini

  - name: "templating syslinux configuration file"
    template:
      src: ../roles/vm-deploy/templates/linux/etc/pxe.cfg
      dest: /dev/shm/pybootd/pybootd/etc/pxe.cfg

  # starting server
  - name: "Starting the server on the helper machine"
    shell: "(python3.7 /dev/shm/pybootd/pybootd.py -c /dev/shm/pybootd/pybootd/etc/pybootd.ini &)"
    async: 45
    poll: 0
